export const list = [
  {
    key: '0',
    name: 'Bunastar',
    position: 'Front end develop',
    duration: '2021/12 ~ 2022/7',
    content: 'Live',
  },
  {
    key: '1',
    name: 'freelance',
    position: 'freelance',
    duration: '2020/6 ~ 2021/12',
    content: '接案',
  },
  {
    key: '2',
    name: 'Ganapati',
    position: 'Front-end Developer',
    duration: '2019/4 ~ 2020/6',
    content: 'fish game, slot',
  },
  {
    key: '3',
    name: 'winner777',
    position: 'Senior Software Developer',
    duration: '2018/6 ~ 2019/4',
    content: 'poker, gamefi(區塊鏈遊戲)',
  },
  {
    key: '4',
    name: 'Cherrytech',
    position: 'Senior Frontend Developer',
    duration: '2017/8 ~ 2018/6',
    content: 'poker(Flash to H5)',
  },
  {
    key: '5',
    name: 'onelab',
    position: 'Clinet developer',
    duration: '2011/4 ~ 2017/2',
    content: 'Slot, Scratch, Poker(actionscript, javascript)',
  },
  {
    key: '6',
    name: '玩美集品',
    position: 'Programmer',
    duration: '2007/12 ~ 2011/3',
    content: '展覽廠商排位系統, FB遊戲, 抽獎遊戲',
  },
  {
    key: '7',
    name: '中菲電腦',
    position: 'Programmer',
    duration: '2006/1 ~ 2007/2',
    content: '銀行財務系統、HR系統、倉庫管理系統在IBM AS/400上',
  },
];
